### ISSUE TITLE
Pas d'envoi de mail de confirmation

### ISSUE THREAD

**Issue by alix-tz** [hipster-philology/pyrrha#157]
Bonjour,

Sur l'application en ligne, j'ai créé un compte mais ne reçois pas d'e-mail de confirmation (SPAM vérifiés). 

Quand je teste la même manip sur une instance local, je ne reçois pas non plus d'email, et j'ai le message suivant :  

```
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/css/font-awesome.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/css/typeaheadjs.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/css/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/css/site.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/js/jquery.min.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/js/bootstrap.bundle.min.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /statics/js/typeahead.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:11] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Oct/2019 09:34:18] "GET /statics/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:22] "GET /account/login HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:32] "POST /account/login HTTP/1.1" 302 -
127.0.0.1 - - [29/Oct/2019 09:34:32] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [29/Oct/2019 09:34:33] "GET /account/unconfirmed HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2019 09:34:40] "GET /account/confirm-account HTTP/1.1" 302 -
127.0.0.1 - - [29/Oct/2019 09:34:40] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [29/Oct/2019 09:34:40] "GET /account/unconfirmed HTTP/1.1" 200 -
send: 'ehlo [127.0.1.1]\r\n'
reply: b'250-ak47\r\n'
reply: b'250-AUTH PLAIN LOGIN\r\n'
reply: b'250-SIZE 52428800\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'ak47\nAUTH PLAIN LOGIN\nSIZE 52428800\n8BITMIME\nENHANCEDSTATUSCODES\nSMTPUTF8'
send: 'AUTH PLAIN AHBvc3RtYXN0ZXJAc2FuZGJveGZhN2E4NzMzMDNjMTQyNWY4ZmRhNzk0N2FhMTk1Njk2Lm1haWxndW4ub3JnAGMzYzdjYzNjNzg1ODE1YTg3MjhhNjI2Njc0NWE3MGRiLWI2MTgzYWQ0LWM3OGQ3NDg3\r\n'
reply: b'535 5.7.0 Mailgun is not loving your login or password\r\n'
reply: retcode (535); Msg: b'5.7.0 Mailgun is not loving your login or password'
send: 'AUTH LOGIN cG9zdG1hc3RlckBzYW5kYm94ZmE3YTg3MzMwM2MxNDI1ZjhmZGE3OTQ3YWExOTU2OTYubWFpbGd1bi5vcmc=\r\n'
reply: b'334 UGFzc3dvcmQ6\r\n'
reply: retcode (334); Msg: b'UGFzc3dvcmQ6'
send: 'YzNjN2NjM2M3ODU4MTVhODcyOGE2MjY2NzQ1YTcwZGItYjYxODNhZDQtYzc4ZDc0ODc=\r\n'
reply: b'535 5.7.0 Mailgun is not loving your login or password\r\n'
reply: retcode (535); Msg: b'5.7.0 Mailgun is not loving your login or password'
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/achague/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/achague/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/sf_host_achague/host_achague/Documents/TIMEUS/Post-OCR_correction/pyrrha/app/email.py", line 17, in _async
    mail.send(msg)
  File "/home/achague/Documents/venv_pyrrha/lib/python3.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/achague/Documents/venv_pyrrha/lib/python3.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/achague/Documents/venv_pyrrha/lib/python3.7/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/home/achague/anaconda3/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/home/achague/anaconda3/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/home/achague/anaconda3/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.0 Mailgun is not loving your login or password')
```

**Comment by PonteIneptique** [comment]
Bonjour @alix-tz ,
Le problème sur l'instance des chartes est forwardé. Pour le problème en local, il faut que je m'y attèle: depuis le passage à une app en ligne (contrairement à l'originelle app locale), je n'ai pas créé de petite fonction dans manage pour activer par défaut les utilisateurs :/
Le plus "simple", c'est sqlite editor et changer la case d'activation :/

**Comment by alix-tz** [comment]
Super ! Effectivement, je suis allée modifier le paramètre "confirmed" dans la table "user" avec SQLite Browser. C'est suffisant comme solution pour le moment. 👍
