### ISSUE TITLE
SQL bug while fetching morph

### ISSUE THREAD

**Issue by MrGecko** [hipster-philology/pyrrha#160]
Don't know much about how it happened since I just caught it in a log (from today) : 
```[2019-10-31 10:11:30,495] ERROR in app: Exception on /controls/3/api/morph [GET]
Traceback (most recent call last):
 File "pyrrha/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near ")": syntax error
...
  File " pyrrha/app/control_lists/views.py", line 211, in search_api
    ).limit(AUTOCOMPLETE_LIMIT)
...
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ")": syntax error
[SQL: SELECT allowed_morph.label AS allowed_morph_label, allowed_morph.readable AS allowed_morph_readable 
FROM allowed_morph 
WHERE allowed_morph.control_list = ? AND () GROUP BY allowed_morph.label
 LIMIT ? OFFSET ?]
[parameters: (3, 20, 0)]
```
It may be about the empty `AND ()` in the query

**Comment by PonteIneptique** [comment]
Possible empty request on autocomplete ?
